config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # Making home page the root page
  root 'home#index'

  get 'home/about', to: 'home#about'
  get 'home/contact', to: 'home#contact'
  post 'request_contact', to: 'home#request_contact'
  get 'home/comedians', to: 'home#comedians'
  
  resources :podcasts do
    resources :comments
    collection do
      get :search
    end
  end

end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/ability.rb
# frozen_string_literal: true
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :manage, Podcast, user_id: user.id
      can :manage, Comment, user_id: user.id
      can :read, :all
    end
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :podcast
  belongs_to :user

  validates :content, :presence => true, length: {minimum: 3}
end

app/models/podcast.rb
class Podcast < ApplicationRecord
  belongs_to :user
  has_many :comments, :dependent => :destroy

  # Thumbnail upload
  has_attached_file :banner, styles: {large: "1500x500>", medium: "500x400>", thumb: "200x150"}
  validates_attachment_content_type :banner, content_type: /\Aimage\/.*\z/

  # MP3 upload
  has_attached_file :audio
  validates_attachment :audio, :content_type => {:content_type => ["audio/mpeg", "audio/mp3"]}, :file_type => {:matches => [/mp3\Z/]}

  # Video upload
  has_attached_file :video, :styles => { :medium => {:geometry => "640x480", :format => 'mp4'}, :thumb => {:geometry => "100x50", :format => 'jpg', :time => 10} }, :processor => [:transcoder]

  validates_attachment_content_type :video, content_type: /\Avideo\/.*\z/

  validates :title, :presence => true, length: {minimum: 3}
  validates :description, :presence => true, length: {minimum: 3}
  # Search podcasts
  def self.search(params)
    podcasts = Podcast.where("title LIKE ? or description LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%") if params[:search].present?
    podcasts
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :podcasts, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :username, :email, :password, :password_confirmation

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def create
    @podcast = Podcast.find(params[:podcast_id])
    @comment = @podcast.comments.create(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to podcast_path(@podcast), notice:
      I18n.t('podcasts.comments.create_success')
    else
      redirect_to podcast_path(@podcast), alert:
      I18n.t('podcasts.comments.create_fail')
    end
  end

  def destroy
    @podcast = Podcast.find(params[:podcast_id])
    @comment = @podcast.comments.find(params[:id])
    if @comment.destroy
      redirect_to podcast_path(@podcast), notice:
      I18n.t('podcasts.comments.delete_success')
    else
      redirect_to podcast_path(@podcast), alert:
      I18n.t('podcasts.comments.delete_fail')
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :podcast_id, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def about
  end

  def contact
  end

  def request_contact
    name = params[:name]
    email = params[:email]
    telephone = params[:telephone]
    message = params[:message]

    if email.blank?
      flash[:alert] = I18m.t('home.request_contact.no_email')
    else
      ContactMailer.contact_email(email, name, telephone, message).deliver_now
      flash[:notice] = I18n.t('home.request_contact.email_sent')
    end

    redirect_to root_path
  end

  def comedians
  end
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  load_and_authorize_resource
  before_action :set_podcast, only: [:show, :edit, :update, :destroy]

  # GET /podcasts
  # GET /podcasts.json
  def index
    # Order in ascending order
    @podcasts = Podcast.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 4)
  end

  # GET /podcasts/1
  # GET /podcasts/1.json
  def show
  end

  def search
    if params[:search].blank?
      @podcasts = Podcast.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 4)
    else
      @podcasts = Podcast.search(params)
    end
  end

  # GET /podcasts/new
  def new
    @podcast = Podcast.new
  end

  # GET /podcasts/1/edit
  def edit
  end

  # POST /podcasts
  # POST /podcasts.json
  def create
    @podcast = Podcast.new(podcast_params)
    @podcast.user_id = current_user.id
    respond_to do |format|
      if @podcast.save
        format.html { redirect_to @podcast, notice: I18n.t('podcasts.new.create_success') }
        format.json { render :show, status: :created, location: @podcast }
      else
        format.html { render :new }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /podcasts/1
  # PATCH/PUT /podcasts/1.json
  def update
    respond_to do |format|
      if @podcast.update(podcast_params)
        format.html { redirect_to @podcast, notice: I18n.t('podcasts.edit.update_success') }
        format.json { render :show, status: :ok, location: @podcast }
      else
        format.html { render :edit }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /podcasts/1
  # DELETE /podcasts/1.json
  def destroy
    @podcast.destroy
    respond_to do |format|
      format.html { redirect_to podcasts_url, notice: I18n.t('podcasts.edit.delete_success') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_podcast
      @podcast = Podcast.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def podcast_params
      params.require(:podcast).permit(:title, :description, :banner, :audio, :video, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/views/comments/_comment.html.erb
<div style="margin-top:2rem">

  <% @podcast.comments.each do |comment| %>
    <fieldset>
      <ol>
        <li>
          <%= current_user.username %>
          <!-- Displays at what time was the comment created. -->
          <%= comment.created_at.strftime('%a %-b %-d, %Y at %l:%M %P') %><br />
          <%= comment.content %>
          <!-- User can delete only the comments he made. -->
          <% if can? :destroy, comment %><%= link_to 'Delete Comment', [comment.podcast, comment], method: :Delete, data: {confirm: 'Are you sure?'} %>
          <% end %>
        </li>
      </ol>
    </fieldset>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@podcast, @podcast.comments.new]) do |f| %>

<div>
  <%= f.text_area :content, rows: 2, cols: 60, placeholder: "Write a comment..." %>
</div>

<div class="btn-holder">
  <%= f.submit "Comment", class:"btn btn_highlight" %>
</div>
<% end %>

app/views/home/about.html.erb
<section class="container">
  <div class="row">
    <div class="col-md-12" style="margin-top:5rem">
      <div class="btn_holder"><br>
        <h2><%= t('home.about.title') %></h2>
      </div><br><br>

      <div class="p-left">
        <p>
          <%= image_tag 'ComedyClubSofiaTwo.jpg', class: "p-left episode_thumbnail" %>
        </p>

        <p>
          The Comedy Club is the first and currently the only comedy club in Bulgaria. We have clubs in Sofia and Plovdiv.<br/><br/>In 2015, comedian Ivan Kirkov founded Comedy Club Sofia in order to promote the stand up comedy genre in Bulgaria.<br/><br/>
          The first year turns out to be extremely difficult and Kirkov is about to go bankrupt and close the club shortly before April 1st, 2016. After Jimmy Carr's risky but extremely successful show in Bulgaria, organized by Comedy Club Sofia and Ivan
          Kirkov, things are back to normal and the Comedy Club is establishing itself as one of the favorite places in Sofia.<br/><br/>
          The first comedians and residents of the club are Vasil Nozharov, Nikola Todoroski, Niki Bankov and Ivan Kirkov. In 2016, Kirkov discovered some of the greatest talents of Bulgarian standup comedy, including Philip of the Comedy Club, Petya Kyupova,
          Alexander Deyanski, Nikolaos Tsitridis, Hristo Radoev, Christian Terziev and others.<br/><br/>More than three years later, there is almost no young person in the country who has never heard of Comedy Club Sofia and Standup Comedy in Bulgaria.<br/><br/>
          The Comedy Club<br/><strong>Sofia Address:</strong> 8 Lege Str<br/><strong>Plovdiv Address:</strong> Joakim Gruev Str
        </p>
      </div>
    </div>
  </div>

</section>

app/views/home/comedians.html.erb
<section class="container">
  <div class="row">
    <div class="col-md-12" style="margin-top:5rem">
      <div class="btn_holder"><br>
        <h2><%= t('home.comedians.title') %></h2>
      </div><br><br>

      <div class="p-left">
        <p>
          <%= image_tag 'ivanKirkov.jpg', class: "p-left episode_thumbnail" %>
        </p>

        <p>
          Ivan Kirkov is the founder and resident of Comedy Club Sofia. His active career in
          standup comedy started in 2012 when he founded Comedy BG. In 2015 he created the first
          and only comedy club in the country - Comedy Club Sofia.
        </p>
      </div>

      <div class="p-left"><br><br><br>
        <p>
          <%= image_tag 'vasilNodjarov.jpg', class: "p-left episode_thumbnail" %>
        </p>

        <p>
          Vasil Nozharov is a resident of Comedy Club Sofia and one of the best standup comedians in Bulgaria.
          His active career began in 2013. Vassil has over 800 standup comedy shows in his career and numerous awards,
          including Comedian of the Year 2016 and 2017.
        </p>
      </div>

      <div class="p-left"><br><br><br>
        <p>
          <%= image_tag 'filip.jpg', class: "p-left episode_thumbnail" %>
        </p>

        <p>
          Philip of Comedy Club Sofia is one of the best standup comedians in Bulgaria and Resident of Comedy Club Sofia.
          His active career began in the spring and summer of 2016 by Open Mic at Comedy Club Sofia. In October 2018
          he became the youngest winner of the Comedian of the Year Comedy Club Sofia Award.
        </p>
      </div>

      <div class="p-left"><br><br><br>
        <p>
          <%= image_tag 'petya.jpg', class: "p-left episode_thumbnail" %>
        </p>

        <p>
          Petya Kyupova is the first female standup comedian in Bulgaria. She is one of the best standup comedians in the country and a resident of Comedy Club Sofia.
          Her active career started in 2016 at Open Mic at Comedy Club Sofia.
        </p>
      </div>

      <div class="p-left"><br><br><br>
        <p>
          <%= image_tag 'nikolay.jpg', class: "p-left episode_thumbnail" %>
        </p>

        <p>
          Nikolay Bankov is one of the first and best standup comedians in Bulgaria and a resident of Comedy Club Sofia.
          His active career started in 2014 by Open Mic at Comedy BG. In 2018 he becomes Comedian of the Year at Comedy Club Sofia, alongside Philip of Comedy Club.
        </p>
      </div>

      <div class="p-left"><br><br><br>
        <p>
          <%= image_tag 'nikolaos.jpg', class: "p-left episode_thumbnail" %>
        </p>

        <p>
          Nikolaos Tsitridis is a resident of Comedy Club Sofia. His active career began in the spring of 2016 at Open Mic at Comedy Club Sofia.
          Nikolaos has hundreds of shows in his career and has participated in 5 stand up comedy shows in Hall 1 of the National Palace of Culture so far.
        </p>
      </div>

      <div class="p-left"><br><br><br>
        <p>
          <%= image_tag 'hristo.jpg', class: "p-left episode_thumbnail" %>
        </p>

        <p>
          Hristo Radoev is one of the most original standup comedians in Bulgaria and the main comedian of Comedy Club Sofia.
          His career began with Open Mic at Comedy Club Sofia in 2016.
        </p>
      </div>
    </div>
  </div>

</section>

app/views/home/contact.html.erb
<section class="container">
  <div class="row">
    <div class="col-md-12" style="margin-top:5rem">
      <div class="btn_holder">
        <h2><%= t('home.contact.title') %></h2>
        <h3><%= t('home.contact.contact_us') %></h3>
      </div>
    </div>
  </div>
  <%= form_tag request_contact_path, method: 'post' do %>
  <div class="row">
    <div class="col-md-12">
      <div class="field"><br>
        <%= label_tag :name %>
        <%= text_field_tag :name, "", style: "width:100%" %>
      </div>

      <div class="field">
        <%= label_tag :email %>
        <%= email_field_tag :email, "", style: "width:100%" %>
      </div>

      <div class="field">
        <%= label_tag :telephone %>
        <%= telephone_field_tag :telephone, "", style: "width:100%" %>
      </div>

      <div class="field">
        <%= label_tag :message %>
        <%= text_area_tag :message, "", style: "width:100%" %>
      </div>

      <div class="actions">
        <div class="btn_holder"><br>
          <%= submit_tag "Send email", class:"btn btn_dark" %>
        </div>
      </div>
        <% end %>
    </div>
  </div>
</section>

app/views/home/index.html.erb
<%= render 'shared/slideshow' %>
<section class="container">
  <div class="row">
    <div class="col-md-12" style="margin-top:3rem">
      <div class="btn_holder">
        <h2><%= t('home.home.welcome') %></h2>
        <div class="mobile_visible btn_holder">
          <%= image_tag "comedyClubSofia.jpg", style:"width:100%; border-radius: 4px;" %>
        </div><br>
        <p>Entertaining people and having fun is our first priority! Join us in our jorney - watch our online podcasts, or be our guest on one of our shows in every city in the country!</p>
      </div>

      <div class="mobile_visible btn_holder">
        <p>What are you waiting for? Join Us!</p>

        <div class="mobile_visible btn_holder">
          <%= link_to 'Sign Up', new_user_registration_path, class:'btn btn_highlight' %>
        </div><br><br><br>

        <h3>The people behind our success.</h3>
        <h4>Our comedians.</h4>

        <p><%= image_tag "actorsAll.jpg", style:"width:100%; border-radius: 4px;" %></p>
        <p><%= link_to 'Comedians', home_comedians_path, class:'btn btn_highlight' %></p><br><br>

        <h3>Who are we?</h3>
        <h4>Get to know us better.</h4>

        <p><%= image_tag "ComedyClubSofiaTwo.jpg", style:"width:100%; border-radius: 4px;" %></p>
        <p><%= link_to 'About', home_about_path, class:'btn btn_highlight' %></p>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('app_title') %></title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'shared/navigation' %>
    </header>

      <% if alert %>
        <div id="notice_wrapper">
            <p class="alert"><%= alert %></p>
          </div>
      <% elsif notice %>
        <div id="notice_wrapper">
            <p class="notice"><%= notice %></p>
        </div>
      <% end %>


    <%= yield %>

    <script>
      $(document).ready(function(){
        setTimeout(function() {
          $('#notice_wrapper').fadeOut("slow", function() {
            $this.remove();
          });
        }, 6500 );
      });
    </script>

    <footer>
      <%= render 'shared/footer' %>
    </footer>
  </body>
</html>

app/views/podcasts/edit.html.erb
<section class="container">
  <div class="row">
    <div class="col-md-12" style="margin-top:5rem">
      <div class="btn_holder">
        <h1><%= t('podcasts.edit.title') %></h1>
      </div>
    </div>
  </div>
      <%= render 'form', podcast: @podcast %>
</section>

app/views/podcasts/index.html.erb
<div class="btn_holder" style="margin-top:5rem">
  <h2><%= t('podcasts.index.title') %></h2><br><br>
</div>

<div id="podcasts-show" class="cf">
  <div class="wrapper">
    <ul class="cf">
      <% @podcasts.each do |podcast| %>
        <li>
          <% if podcast.banner.present? %>
            <%= image_tag podcast.banner.url(:thumb) %>
          <% else %>
            <%= image_tag "noimage.jpg" %>
          <% end %>
          <div class="overview">
            <h2><%= link_to podcast.title, podcast, class: 'title-text' %></h2>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div><!-- .row -->
<div class="main-pag">
  <div class="fixer-pag">
    <%= will_paginate @podcasts %>
  </div>
</div>

app/views/podcasts/show.html.erb
<section class="container">
  <div class="row">
    <div class="col-md-12" style="margin-top:5rem">
      <div class="btn_holder"><br>
        <p>
          <!-- If an episode is created with an image, display it -->
          <% if @podcast.banner.present? %>
            <%= image_tag (@podcast.banner.url(:medium)), class:"episode_thumbnail" %>
          <% else %>
            <!-- Else, display the NoImage image.-->
            <%= image_tag "noimage.jpg", class: "episode_thumbnail" %>
          <% end %>
        </p>
      </div>

      <div class="btn_holder">
        <p>
          <strong><%= @podcast.title %></strong>
        </p>
      </div>

      <div class="btn_holder"><br>
        <p>
          <%= @podcast.description %>
        </p>
      </div>

      <div class="btn_holder"><br>
        <p>
          <!-- If a podcast is created with a mp3, display it -->
          <% if @podcast.audio.present? %>
            <%= audio_tag(@podcast.audio.url, controls: true, style: "width:70%") %>
          <% end %>
        </p>
      </div>

      <div class="btn_holder"><br>
        <p>
          <!-- If a podcast is created with a video, display it -->
          <% if @podcast.video.present? %>
            <%= video_tag(@podcast.video.url, controls: true, type: "video/mp4", style: "width:70%") %>
          <% end %>
        </p>
      </div>

      <div class="btn_holder"><br><br>
        <div class="btn-group">
          <% if can? :update, @podcast %><%= button_to 'Edit', edit_podcast_path(@podcast), :method => :get, class: "btn btn_highlight", style: "margin-right: 7rem" %>
          <% end %>
          <% if can? :destroy, @podcast %><%= button_to 'Delete', @podcast, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn_dark' %>
          <% end %>
        </div>
      </div>

      <h3 style="margin-top:8rem"><%= t('podcasts.comments.title') %></h3>

      <!-- Comments Partial -->
      <div>
        <%= render 'comments/comment' %>
      </div>

      <!-- Form Partial -->
      <!-- If user is logged in -->
      <% if current_user %>
      <div>
        <%= render 'comments/form' %>
      </div>
        <!-- If user is not logged or signed in -->
      <% else %>
        <div class="btn_holder">
          Please
          <%= link_to 'Sign In', new_user_session_path %>
          or
          <%= link_to 'Sign Up', new_user_registration_path %>
          to add a comment.
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <h5><%= link_to 'Comedy Club', root_path, class:'navbar-brand' %></h5>
        <h6><%= link_to 'Comedians', home_comedians_path, class:'a' %></h6>
        <h6><%= link_to 'Contact Us', home_contact_path, class:'a' %></h6>
        <h6><%= link_to 'About', home_about_path, class:'a' %></h6>

      </div><!-- col-md-4 -->

      <div class="col-md-4">
        <h5><%= t('footer.address') %></h5>
        <p id="map" </p>
          <script>
            // Initialize and add the map
            function initMap() {
              // The location of Uluru
              var uluru = {lat: 51.241920, lng: -0.585900};
              // The map, centered at Uluru
              var map = new google.maps.Map(
                document.getElementById('map'), {zoom: 15, center: uluru});
                // The marker, positioned at Uluru
              var marker = new google.maps.Marker({position: uluru, map: map});
            }
          </script>
          <!--Load the API from the specified URL
          * The async attribute allows the browser to render the page while the API loads
          * The key parameter will contain your own API key (which is not needed for this tutorial)
          * The callback parameter executes the initMap() function
          -->
          <script async defer
          src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAq96yv3MIDUWM26cc_GWtRdfZU1KQpR3c&callback=initMap">
          </script>
        </div><!-- col-md-4 -->

      <div class="col-md-4">
        <h5><%= t('footer.follow_us') %></h5>
        <h6>
          <%= link_to "https://twitter.com/?lang=en-gb" do %>
          <%= image_tag 'twitter.png', :size => "42x42", class: "image" %>
          <% end %>
        </h6>
        <h6>
          <%= link_to "https://www.youtube.com/channel/UCEf1BL_OqYKu2-CVuuMoE2Q" do %>
          <%= image_tag 'youtube.png', :size => "40x40", class: "image" %>
          <% end %>
        </h6>
        <h6>
          <%= link_to "https://en-gb.facebook.com" do %>
          <%= image_tag 'facebook.png', :size => "39x39", class: "image" %>
          <% end %>
        </h6>
      </div><!-- col-md-4 -->
    </div><!-- row -->

    <div class="row top-margin bottom-margin">
      <div class="col-lg-6">
      </div><!-- col-lg-6 -->

      <div class="col-lg-6">
        <div class="form-inline mt-2 mt-md-0 floatr">
          <%= form_tag search_podcasts_path, method: :get do %>
          <%= text_field_tag :search, nil, placeholder: "Search", class: "form-control mr-sm-2 bg-dark form-border" %>
          <%= submit_tag "Search", class: "btn btn_highlight my-2 my-sm-0" %>
          <% end %>
        </div>
      </div><!-- col-lg-6 -->
    </div><!-- row -->
  </div><!-- container -->

  <section class="bg-dark">
    <div class="container">
      <div class="row">
        <div class="col-lg-6">
          <span class="floatr" color:"#eeeeee">2019 &copy; Comedy Club</span>
        </div><!-- col-lg-6 -->
      </div><!-- row -->
    </div><!-- container -->
  </section>
</footer>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <%= link_to 'Comedy Club', root_path, class:'navbar-brand' %>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <% unless user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Podcasts', podcasts_path, class:'nav-link' %>
        </li>

        <li class="nav-item">
          <%= link_to 'Comedians', home_comedians_path, class:'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Podcasts', podcasts_path, class:'nav-link' %>
        </li>

        <li class="nav-item">
          <%= link_to 'Comedians', home_comedians_path, class:'nav-link' %>
        </li>

        <li class="nav-item">
          <%= link_to 'Create a podcast', new_podcast_path, class:'nav-link' %>
        </li>
      <% end %>
    </ul>

    <ul class="navbar-nav">
      <% unless user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class:'nav-link' %>
        </li>

        <li class="nav-item">
          <%= link_to 'Sign in', new_user_session_path , class:'nav-link' %>
        </li>
      <% else %>

        <li class="nav-item">
          <%= link_to 'Account Settings', edit_user_registration_path, class:'nav-link' %>
        </li>

        <li class="nav-item">
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class:'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_slideshow.html.erb
<div id="myCarousel" class="carousel slide d-none d-md-block" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <%= image_tag "comedyClubSofia.jpg" %>
      <div class="container">
        <div class="carousel-caption d-none d-md-block text-left">
          <h1><%= t('carousel.welcome') %></h1>
          <p>We are the first and only comedy club in Bulgaria!</p>
          <p><%= t('carousel.join_us') %></p>
          <p><%= link_to 'Sign Up', new_user_registration_path, class:'btn btn_highlight' %></p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag "ComedyClubSofiaTwo.jpg" %>
      <div class="container">
        <div class="carousel-caption d-none d-md-block text-right">
          <h1><%= t('carousel.who_are_we') %></h1>
          <p>Get to know us better.</p>
          <p><%= link_to 'About', home_about_path, class:'btn btn_highlight' %></p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag "actorsAll.jpg" %>
      <div class="container">
        <div class="carousel-caption d-none d-md-block text-right">
          <h1><%= t('carousel.people_behind_sucess') %></h1>
          <p>Meet our comedians.</p>
          <p><%= link_to 'Comedians', home_comedians_path, class:'btn btn_highlight' %></p>
        </div>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>